import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={`${styles.grid} `}>
          <div className={`${styles.card} cursor-pointer`}>
            <h2>Learn JavaScript</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </div>

          <div className={`${styles.card} cursor-pointer`}>
            <h2>Learn Redux</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </div>

          <div
           
            className={`${styles.card} cursor-pointer`}
          >
            <h2>Learn Next Js</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </div>

          <div
            className={`${styles.card} cursor-pointer`}
          >
            <h2>Learn Node Js</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
